name: Sincronizacao Automatica do Fork

on:
  schedule:
    - cron: '0 */6 * * *' # Executa automaticamente a cada 6 horas
  workflow_dispatch: # Permite que você force a execução manualmente se quiser

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sincronizando com o Upstream
        uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          owner: nfephp-org
          base: master
          head: master
