name: Sincronizacao Automatica do Fork

on:
  schedule:
    - cron: '0 */6 * * *' # Executa automaticamente a cada 6 horas
  workflow_dispatch: # Permite que você force a execução manualmente se quiser

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Sincronizando com o Upstream Oficial
        env:
          GH_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          gh repo sync ${{ github.repository }} --branch master
